### ISSUE TITLE
MP JWT 1.2 for 21.0.0.3

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/blogs#1168]
Blog post for MP JWT 1.2 @teddyjtorres please provide details

The MP JWT 1.2 blog post will outline the new MP Config properties that were added to the spec, support for JSON Web Encryption (JWE) tokens, and enhanced algorithm support. The blog will include usage examples for the new functionality as well.

MP 4.0 blog posts are expected to be done by **March 12**.

The Open Liberty release notes are presented in three places:
- [Open Liberty blog](https://openliberty.io/blog/) (GA and beta features; [example](https://openliberty.io/blog/2020/05/07/EJB-persistent-timers-20005.html))
- [Red Hat Runtimes release notes for Open LIberty](https://access.redhat.com/documentation/en-us/open_liberty/2020/) (GA features only; [example](https://access.redhat.com/documentation/en-us/open_liberty/2020/html/release_notes_for_open_liberty_20.0.0.5_on_red_hat_openshift_container_platform/features))
- [Red Hat Developer blog](https://developers.redhat.com/blog/) (GA features only; [example](https://developers.redhat.com/blog/2020/05/13/open-liberty-20-0-0-5-brings-updates-to-ejb-persistent-timers-coordination-and-failover-across-members/))

## 1. Open Liberty release blog post

The Open Liberty release blog post is written in asciidoc and pushed to the [OpenLiberty/blogs](https://github.com/openliberty/blogs) repo. The repo README contains [instructions on how to create, build, and review](https://github.com/OpenLiberty/blogs/blob/prod/README.md) the post, including a template file to help you.

Follow the instructions in the README and the template file to complete the following tasks:

- [x] Create a draft release blog post in asciidoc, build to [the draft site](https://draft-openlibertyio.mybluemix.net/blog/), and create a PR to the `staging` branch with a link to the post on [the draft site](https://draft-openlibertyio.mybluemix.net/blog/). Add all the reviewers (see below) to the PR so that they can add all their review feedback and approvals in the PR.
- [ ] Get the draft post reviewed by:
  - [x] All the people who contributed the content to the blog post.
  - [ ] At least one of the following people: @mbroz2
- [ ] Agree with @mbroz2 which feature will lead this blog post, then write a title, slug, summary first paragraph, and SEO front matter appropriately.
- [ ] Get the post approved by @mbroz2.
- [ ] On release day (usually a Friday) @mbroz2 will publish the post.

## 2. Red Hat Runtimes release notes for Open Liberty

The release notes are automatically built from the asciidoc release blog post. This is done by using the appropriate tags in the asciidoc source and then the Red Hat documentation build includes the tagged sections in the release notes. The tags ensure that information in the blog post that is not relevant to the Red Hat Runtimes release are omitted from the Red Hat Runtimes release notes.

- [ ] In the asciidoc source of the draft release blog post, check that the include tags are in the correct places in the asciidoc source file:
  - [ ] `// tag::intro[]` (before the first paragraph)
  - [ ] `// end::intro[]` (after the link to the list of fixed bugs)
  - [ ] `// tag::run[]` (before the Maven coordinates)
  - [ ] `//end::run[]` (after the Dockerfile entry)
  - [ ] `//tag::features[]` (before the first GA feature section)
  - [ ] `//end::features[]` (after the last GA feature section)
- [ ] In [the release notes file](https://raw.githubusercontent.com/PurpleLiberty/docs/master/releasenotes/master-remote.adoc) (in a separate repo on GitHub), find the include statement in the **Features** section of the release notes. Edit the file name part of the include statement so that it targets the new Open Liberty release blog post .adoc file. Don't change anything else. Work with the ID team if they contact you to resolve any problems when the Red Hat build is run.

## All done?

Check that you've completed every task above. Select each check box to confirm that you have before closing this issue.

**Comment by Rwalls1** [comment]
@teddyjtorres @ayoho  

# ID review

## Intro
- Change "The MicroProfile JWT specification allows using a JSON Web Token (JWT)” to “The MicroProfile JWT allows you to use a JSON Web Token (JWT)” to avoid the awkward phrasing and to make it clear what JWT refers to at the beginning of the blog since the abbreviation is used throughout.
- I don’t think the phrase, “This blog is broken into the following sections:” adds much value. I think you should change it to something like, “The following sections describe the different features that are added with MicroProfile JWT version 1.2:”
## New MP Config properties
- Change "the `<mpJwt>` element in Open Liberty’s server.xml” to “the `<mpJwt>` element in Open Liberty’s server.xml file” to more clearly identify what `server.xml` is referring to.
- Change “Whenever there is an equivalent server.xml attribute for an MP Config property, the server.xml attribute  to “Whenever there is an equivalent attribute in the server.xml file for an MP Config property, the attribute” to maintain clarity.
- Change “`tokenHeader` attribute of the `<mpJwt>` server.xml element:” to "tokenHeader attribute of the `<mpJwt>` element in the server.xml file:”
- Change “the `cookieName` attribute of the `<mpJwt>` server.xml element to “the `cookieName` attribute of the `<mpJwt>` element in the server.xml file:”
- Change “or `tokenHeader` server.xml attribute to “or `tokenHeader` attribute.
- Change "cookieName attribute to be recognized.” to "cookieName attribute in the server.xml file to be recognized.
- Typo: "create list of allowable audience values” to "create a list of allowable audience values”. 
- Change "At least one of these” to “At least one of these values”
- Change "can also be specified in the `<mpJwt>` server.xml element using the `keyManagementKeyAlias` attribute” to "can also be specified by using the `keyManagementKeyAlias` attribute of the `<mpJwt>` element in the server.xml file” ﻿
- Change "JWE tokens whose payload is not a nested JWS” to "JWE tokens that contain a payload that is not a nested JWS” to avoid awkward phrasing
- Change "the public key algorithm used for” to "the public key algorithm that is used for”
## Examples
- I think you should change the title of this section to something more meaningful that highlights its relevance to readers. I think you should change the title to something like, “MP JWT 1.2 configuration examples” or “Examples of MP JWT 1.2 configuration”.
- Typo: Change “as shown here.” To “as shown here:”
- Change "a 401 will be returned” to “a 401 error will be returned”
- " As with the other MP Config properties, there are server.xml alternatives available.” to “As with the new MP config properties, there are alternative attributes that can be specified in the server.xml file for earlier MP config properties.”
- Change "A successful response means that” to something like “A successful response means that the following details are true:”
- Typo: Change "using the `privateKey.pem` key to “by using the privateKey.pem key”
- Typo: Change “using the publicKey.pem key “ to “by using the publicKey.pem key “
