### ISSUE TITLE
Bad link for "Open Liberty 19.0.0.9" in Reactive Messaging post

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/blogs#131]
https://openliberty.io/blog/2019/09/13/microprofile-reactive-messaging.html

The link in "Get Open Liberty 19.0.0.9" points to the blog post itself?

@hutchig @Azquelt

**Comment by Azquelt** [comment]
I've raised #132 to correct the URL of the 19.0.0.9 blog post. Not sure if that's the best way to fix the issue or whether we should change the links from other blog posts.

I also don't know if we can create a redirect from the old misspelled URL.

Don't think @lauracowen is in today and I'm not sure who else can merge things into this repo.

**Comment by lauracowen** [comment]
Okay, I think I follow:
1. Rename the file `2019-09-13-microprofile-reactive-messsaging-19009.adoc` to `2019-09-13-microprofile-reactive-messaging-19009.adoc` (double-s, not triple-s). Create PR and assign to me.
2. Add entry to https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/webapp/WEB-INF/redirects.properties to point from the old URL to the new URL (so that anyone following a link from Twitter, where we've shared the old URL, will be redirected tot he new URL). Create PR and assign to me.
3. When both PRs are merged, test the link in the blog post in YK's comment at the top of this issue.

**Comment by Azquelt** [comment]
1 & 2 done, thanks @lauracowen 

#132 and OpenLiberty/openliberty.io#1388

**Comment by lauracowen** [comment]
Fixed
