### ISSUE TITLE
Open Liberty with OpenJ9 blog

### ISSUE THREAD

**Issue by gljrobinson** [OpenLiberty/blogs#1566]

**Comment by gljrobinson** [comment]
@yeekangc is this related to any of the blogs on the community site?

**Comment by gljrobinson** [comment]
Perhaps a walk through of using Liberty with Open J9 through IBM Semeru Runtimes, point to other existing resources around advantages.

**Comment by yeekangc** [comment]
@jamiecoleman92 indicated he will get started on this blog post this week.

**Comment by jamiecoleman92** [comment]
[Open Liberty & Semeru Blog.docx](https://github.com/OpenLiberty/blogs/files/8842903/Open.Liberty.Semeru.Blog.docx)
Here is the latest version of the blog post. @yeekangc if you could give it a quick review that then I will convert it to ASCII Doc and make a PR.

**Comment by yeekangc** [comment]
@jamiecoleman92, you can submit a PR with the draft and we can iterate on it.

Can we dive deeper into the technical aspects and advantages of OpenJ9 as a VM?  e.g., how it goes well with Liberty for cloud-native workloads?  Is there any perf data we can share?  Cc @vijaysun-omr.

Also, I am not sure we need to repeat what is Open Liberty since this is the Open Liberty blog.

It's "IBM Semeru Runtimes" and we should use it as such (and correctly).  Cc @rhagarty in case he has comments what more we can consider in terms from the perspective of OpenJ9/IBM Semeru Runtimes.

@lauracowen, can you take a look at the draft and offer your thoughts too when you have a moment?

**Comment by vijaysun-omr** [comment]
I agree with YK, the JDK distribution is what is referred to as "IBM Semeru Runtimes", the JVM's name is Eclipse OpenJ9. We should be clear in expressing that so that users also see the right terminology (in Semeru's case, it is still fairly new).

There are some performance results with the OpenJ9 JVM shown on openliberty.io itself and we should probably link to that homepage. There are also other blogs such as https://openliberty.io/blog/2019/10/30/faster-startup-open-liberty.html that talk about the one second startup time that you mention in the blog post.

**Comment by vijaysun-omr** [comment]
There is also https://www.eclipse.org/openj9/performance/ that lists some information about Eclipse OpenJ9's characteristics including some quotes from people who have tried it.

**Comment by jamiecoleman92** [comment]
Thanks for the feedback @yeekangc & @vijaysun-omr 
I will incorporate the above and create a PR with everything in markdown.
@rhagarty if you can think of anything I should add let me know in a comment here.

**Comment by lauracowen** [comment]
Some thoughts as I read through the draft in the .doc file above:
* I agree, we don't need the section about Open Liberty.
* I feel that there's a lot of "tell" and not "show". I don't mean there needs to be a code demo; just that there are a lot of "best", "perfectly matched", "great" etc claims that aren't clearly evidenced. So it comes across as a bit marketing-y (early on at least, which is when we'll lose the reader).
* I didn't follow what the flow was when the second paragraph starts "The reality is..." - it implies some comparison with what was said in the first para but I'm not sure what was unrealistic in the first para?
* Title needs to be a bit more specific I think. A perfect stack for what? Or maybe don't say perfect stack (which doesn't really tell you anything by itself) and, instead, give a real example of where they work well together? Is there a particular use case we can hook on to (without looking like we exclude others?)?
* By the time you get to the "Why these technologies are a great match" is a long way into the post. This question should really have been answered much sooner in the post, then expanded on in more detail later in the post. Don't be mysterious! :) 



What are the key benefits we should call out in this post?
* performance benefits - start-up time, throughput, ramp-up time(?).
* Usability benefits (like what?).
* Anything else?

I think these need to be stated right up-front so that readers get some info from the first para or two and can stop reading if they're not interested or can carry on if they are. Then in the rest of the post expand on them in more detail. Eg maybe a paragraph per benefit?

**Comment by jamiecoleman92** [comment]
I am finished making the updates suggested above. Who is best to give my blog post another review?

**Comment by jamiecoleman92** [comment]
Also @lauracowen am I allowed to use images and if so could I use the performance comparison image on this site in this blog?
https://www.eclipse.org/openj9/performance/

**Comment by lauracowen** [comment]
Definitely use images if you can find some. Talk to @vijaysun-omr about what's appropriate. From a licencing perspective, check what Eclipse's licence is.

**Comment by jamiecoleman92** [comment]
@lauracowen I think the image is available under the EPL licence so I should be okay to use it but I am not the best at determining T&Cs. This is the most relevant info I could find on it's usage:
"To the extent you wish to upload, submit, or otherwise make Non-Code Content (as defined below) available to the Eclipse Foundation and/or the Members and/or users of this Web site, you may make that material available under the terms and conditions of the EPL or any other license stipulated for that purpose at [www.eclipse.org/legal](https://www.eclipse.org/legal/). Non-Code Content is Content for which you own or control all rights, and which is not program code intended to be submitted to a Project (or documentation related to such code) and which is not Stored Information. For example, Non-Code Content would include white papers, dissertations, articles or other literary works, power point presentations, encyclopedias, anthologies, wikis, blogs, diagrams, drawings, sketches, photos or other images, audio content, video content and audiovisual materials."

**Comment by jamiecoleman92** [comment]
@vijaysun-omr have you every used that image and do you know what the T&C's are around it's usage?

**Comment by jamiecoleman92** [comment]
Alright I have a draft ready to review in Asciidoc @GraceJansen & @lauracowen

**Comment by vijaysun-omr** [comment]
I have asked Tony Renaud about the licensing question even though I am thinking that it is probably okay.

**Comment by jamiecoleman92** [comment]
Any update @vijaysun-omr? If not I will just post it without an image.

**Comment by aprenaud** [comment]
Yes, the license permits public display of contributed works, and the requirements make no mention of attribution other than not removing any trademarks, copyright, patent, trademark, attribution notices etc that already exist.

**Comment by gljrobinson** [comment]
Aiming to publish this the week commencing the 15th August

**Comment by gljrobinson** [comment]
This has now been published: https://openliberty.io/blog/2022/08/19/open-liberty-semeru-performance.html
