### ISSUE TITLE
Add Travis automation to auto host new commits

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/blogs#4]
When merges are made to `master`, we can add some Travis CI automation to rebuild our test environments to host new blog commits.

**Comment by lauracowen** [comment]
Is this something we should still do? I'm not sure I understand what it's about. @ellenwylie @steven1046

**Comment by steven1046** [comment]
I think so. When new blog commits are pushed to master, it doesn't rebuild draft-openlibertyio.mybluemix.net automatically and needs to be triggered manually. Is this something that you still need @lauracowen?

**Comment by lauracowen** [comment]
When posts are pushed to master, they're usually still in the `drafts` folder, so a rebuild isn't necessary. It's only when they appear in `publish` folder in `master` that the rebuild is needed. I accept stuff into `drafts` before it's ready to publish to do final edits on it more easily (rather than leaving everything in PRs).

I guess Travis probably can't spot that level of granularity (updates in the `publish` folder only)?

**Comment by lauracowen** [comment]
@mbroz2 @steven1046 I guess my comment about `drafts` vs `publish` folder will be out-of-date when you tidy up the branches. What should I do with this issue?

**Comment by mbroz2** [comment]
Correct, the above will be invalid once the branch cleanup occurs (https://github.com/OpenLiberty/openliberty.io/issues/1517).  However, I don't think we're ready to finalize what travis should build when until we've outlined the mapping between the new branch names and the non-prod sites.  I'm also not sure what is the intent of this issue or preference of the docs team regarding when to auto-rebuild.  I don't think Travis could handle the load of a rebuild being submitted every time a draft branch is updated (should not be a problem for staging branch, and should be unnecessary for prod since that will be the production site), especially since this would likely be draft branch from multiple repos.  I'd like to leave this open for now and have a discussion regarding what exactly is being requested

**Comment by lauracowen** [comment]
Closing this because it's superceded by the branch reorganisation and then by the new automation stuff @mbroz2 is doing on a wider basis than just the blog.
