### ISSUE TITLE
Blog post on preview release of Open Liberty Tools IntelliJ extension

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/blogs#615]
The purpose of this blog post is to announce the preview release of the [Open Liberty Tools IntelliJ extension](https://github.com/OpenLiberty/open-liberty-tools-intellij) so that developers may start trying out the extension and provide feedback.

**Comment by lauracowen** [comment]
(comment I posted in slack chat)
The video is displaying too small to see the details https://draft-openlibertyio.mybluemix.net/blog/2020/08/12/open-liberty-tools-intellij.html and when I go full screen the resolution is poor.

On youtube itself, the resolution still isn’t great (I think?): https://www.youtube.com/watch?v=4qjHNYE7pSo so when I go to embed the video again at a higher resolution it doesn’t offer me anything higher than what you embedded it in in the first place.

Do you have a higher resolution version of the video because I don’t think we can publish this one (it’s not readable)?

The audio is lovely and clear so it would be a shame not to include it.

Honestly I also think it’s a bit long (at over 5 mins) but can include it as it is if you can improve the visual quality because the info is also provided (I think?) in the text of the blog post.

Could you provide a screenshot (in here is fine) of the dev dashboard that we can include in the post itself too, pls?

**Comment by lauracowen** [comment]
https://openliberty.io/blog/2020/09/03/open-liberty-tools-intellij.html
