### ISSUE TITLE
The reactive guides and reaching 50 guides

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/blogs#741]

**Comment by lauracowen** [comment]
https://draft-openlibertyio.mybluemix.net/blog/2020/09/23/reactive-developer-guides.html

**Comment by mbroz2** [comment]
Feedback for existing content
1. Instead of the title being focused on one particular guide, personally I'd prefer a title that's focus on the guides overall, either 'achievement focused' like "openliberty.io Milestone: now hosting over 50 guides!" or "For our 3rd Birthday, we got more guides!" (don't use that one :D )  or a bit more 'end-user focused' like "With over 50 guides, a new skill is right right around the corner" or "With over 50 guides, 15 minutes is all you need to ["dive into a" or "familiarize yourself with"] a new technology!" 
2. "which we rather proud of" is missing "are"
3. "continuing learning" -> "continue learning"
4. I think a vertical list would be easier to consume visually (similar to the guide list under "Learning to write cloud-native Java microservices")
![image](https://user-images.githubusercontent.com/3076261/92783682-9c722d00-f36b-11ea-83d9-b64953e132b5.png)
5. I think we can drop "That will help us prioritise the guide if we agree that it’s needed (e.g. doesn’t unnecessarily overlap with other guides)."
6. Consider changing "Learning to write reactive Java microservices" to something more general like "Learning through our guides" as the section is (correctly) more-so focused on our guide structure/flow, rather than that particular reactive guide, and it just uses that guide as an example.
7. "Will there be new guides in future?" "Will there be new guides in **the** future?"

Suggestions for additional content:
1. Mention the low barrier to entry (no knowledge is required on a topic; minimal prereqs, and zero prereqs for interactive guides).  Something along the lines of "Each guide makes no assumptions of prior knowledge of a topic, and guides you from beginning to end (but hey, if you're intermediate, just use the Table of Contents to skip forward to a specific part).  Prerequisites are also kept to a minimum, and if you don't want to bother with any code on your local machine, take a look at our (interactive guides)[link] which only require a browser."
2. Mention short time commitment ~"Nowadays it's rare for us to have a day or two to spend investigating a topic, but no worries as the majority of the guides can be accomplished in just 15-20 minutes"
3. Maybe at the end where we talk about future guides we can have something like "To stay up to date with our new guides, subscribe to our twitter handle or bookmark https://openliberty.io/guides/?search=new&key=tag"

**Comment by lauracowen** [comment]
https://openliberty.io/blog/2020/09/24/reactive-developer-guides.html
