### ISSUE TITLE
Changes to imagesdir

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/blogs#773]
We specify `imagesdir: /` in one of the templates, and then use image: img/blog/... when specifying an image. We should either remove the imagesdir property and use slash in the image path, e.g. /img/blog... or keep imagesdir but change it to /img/blog/ so that the images won't have to specify /img/blog/ in their path. Also, this property only exists in one template out of the four so we probably want it in all templates.

**Comment by lauracowen** [comment]
I think we can set it to anything as long as what’s in the image path can be prefixed by RH in their Red Hat Runtimes builds of the release notes (from our GA release blog post). We can't use `/img/blog` in the image path because that was the problem in the first place - RH couldn't prefix it with whatever it was they use.

Can we set the attribute globally to /img/blog/ so that we can just use the image file name without the image path (though we'd need to update all past posts), and we don’t need it in the template at all? 

Yes, all the templates should be consistent, whatever we do - RH only needs the release blog post but it’s confusing for post authors when it’s inconsistent.

**Comment by gljrobinson** [comment]
@steven1046 Is this work now complete? Whats the status of this issue?

**Comment by steven1046** [comment]
I'm looking into if we can set the imagesdir for the posts somewhere common without affecting the guides' images.

**Comment by steven1046** [comment]
Writing some notes down:
We can specify imagesdir in the jekyll config:
```asciidoctor:
  base_dir: :docdir
  safe: 0
  attributes:
    - icons=font
    - source-highlighter=coderay
    - coderay-linenums-mode=inline
    - coderay-linenums=true
    - coderay-css=class
    - allow-uri-read
    - imagesdir=/img/blog/@ # The @ symbol at the end lets guides and other documents override the imagesdir value
```

This will allow blogs to not have to specify the imagesdir property. Guides can still override their own imagesdir in the guide .adoc files. 

I tried to specify the imagesdir per layout type, but per Dan Allen, we cannot define imagesdir per scope/layout. It can only be set globally or in the document.

**Comment by gljrobinson** [comment]
Hi @steven1046 is there more we need to do here to resolve this issue?

**Comment by steven1046** [comment]
I'm having discussions about it and will update you when ready @GraceJansen.

**Comment by steven1046** [comment]
Closing this issue because we can't change the imagesdir per layout (blog, guide, etc) and it's not worth setting the whole site imagesdir to /img/blog/ if other types of documents have to override it.

**Comment by steven1046** [comment]
Until 21.0.0.6 we'll keep the imagesdir as `/` and then after 21.0.0.7 we can update the templates to use imagesdir: `/img/blog/`.
