### ISSUE TITLE
Blog post for using the  Log Forwarding API on OCP 

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/blogs#848]
Blog post that details how to configure your OCP cluster to forward Open Liberty logs to an external Splunk instance using the Log Foward API.

**Comment by gljrobinson** [comment]
Issue #651 is a duplicate, this is the one we should be using. 
@dmuelle

**Comment by gljrobinson** [comment]
@dmuelle could you move this into the editing collumn and could you assign yourself to this please. thanks

**Comment by dmuelle** [comment]
Hi @Channyboy, I did an initial pass of ID edits for style and clarity in this PR: https://github.com/OpenLiberty/blogs/pull/928, for which I've requested your review

I have some more content review questions that I will post to this issue but first I'd like to review the updated draft once the PR has been merged and the draft rebuilt.

If anything in the PR doesn't make sense or needs more work, just let me know. Thanks!

**Comment by dmuelle** [comment]
Content review questions:

## Intro

* What is the role of the Fluentd server? I know that it "redirects the forwarded logs to Splunk by using Splunk's HTTP Event Collector (HEC) API", but why is it needed? Is it not possible to for the Log Forwarding API to send the logs directly from OpenShift to Splunk? I feel like a sentence to explain would be helpful as Fluentd config is a big part of the task.

## Configuring the Log Forwarding API

Step 3 has some issues. It looks like the config in the sample file is not current with the info that we link to for OCP 4.6. For example, there's no mention in the OCP 4.6 doc of `logs.app`, `logs.infra`, or` logs.audit` as pipeline inputs. Also, the inputs are now specified by `InputRefs` rather than `InputSource`, which is no longer mentioned in the OCP doc. And the `InputRefs` also have to be configured in an `Inputs` section. Can you check the OCP 4.6 doc for the Log Forwarding API and update the examples as needed? I started to do it myself but there are enough differences to where I'm afraid I'll make a mess of it.

In general, I think we can greatly simplify the Log Forwarding API example config to show a single example file for the minimum config and then point out to Red Hat for more detailed info: 
- I don't we need to show two whole example files just to explain how to set up the insecure connection. Instead, we could just show a single file and make one of the output configs in it insecure. 
 - Instead of having a separate example for the endpoint config, just use the example IP value directly in the example file. 

## Viewing Logs and Setting up the Splunk Dashboard

step 1 says "Go to Search & Reporting"
Where is that? Is it in the OpenShift console?

**Comment by Channyboy** [comment]
Intro:
The Log Forwarding API's _forward_  `type` triggers their code to automatically configure things in the background.  The way it's set up it can only _forward_ the logs to another fluentd server where we can  configure ourselves however we like. (i.e to splunk).
But also. As you pointed out, in 4.6, this `forward` `type` is now called `fluentdForward`.

Configuring the Log fowarding api:
Yes. names/labels have changed in 4.6. I will take a look and revise.

```
I don't we need to show two whole example files just to explain how to set up the insecure connection. Instead, we could just show a single file and make one of the output configs in it insecure.
```
Perhaps we can just show the example. It's possible somebody might run through the blog copy and pasting. Especially if the person is new and inexperienced with all the topics involved. We were hoping to spell out as many things as possible to make it _easier_.


```
Instead of having a separate example for the endpoint config, just use the example IP value directly in the example file.
```
Ah, the _original config_ is the sample from the RedHat site (i.e with the splunk-fluentd-forward.offcluster.com:24224). I guess once again we were trying to spell out what needed to be done more explicitly with the extra endpoint example. By pointing it out at least anybody who was _struggling_ would know it is important.

Splunk:
This is on the Splunk's UI/front-end.

**Comment by dmuelle** [comment]
suggestion to simplify step 3:

3. Create the `log-forward-instance.yaml` file. Configure the outputs and pipelines.

- The `outputs` section of the file specifies where to send the logs. To establish a *secure* connection to an output, you must specify a *secret*, such as the one that you created in step 2b. If you want to use an insecure connection for test purposes, you can omit the secret from your output configuration.
- The `pipelines` section of the file specifies which log types are sent to the configured outputs. 

The following sample `log-forward-instance.yaml` file uses secure connections and defines two outputs: `elasticsearch,` which routes to an internal Elasticsearch instance and `fluentd-forward`, which routes to the instance of Fluentd that forwards the logs to Splunk. Each log type and its corresponding output reference is defined in the `pipelines` section:

-----updated 4.6 example goes here-------

For more information, see [Forwarding logs using the Fluentd forward protocol](https://docs.openshift.com/container-platform/4.6/logging/cluster-logging-external.html#cluster-logging-collector-log-forward-fluentd_cluster-logging-external). Make sure to consult the documentation for your version of OpenShift, as the pipeline configuration for version 4.6 is slightly different than the preceding versions.

**Comment by gljrobinson** [comment]
@dmuelle can this be closed? I see it's already been published on the OL site

**Comment by dmuelle** [comment]
I'm not aware of any reason to keep it open- would you agree @Channyboy ?
