### ISSUE TITLE
Blog promoting Open Liberty Backend Implementation for RealWorld

### ISSUE THREAD

**Issue by dshimo** [OpenLiberty/blogs#924]
Blog promoting an Open Liberty backend implementation for RealWorld's Conduit Application
Uses MicroProfile and references OL guides

RealWorld: https://github.com/gothinkster/realworld
OL Repo: https://github.com/OpenLiberty/openliberty-realworld-example-app

**Comment by dmuelle** [comment]
## ID Review

Hi @dshimo , nice work! The post gives a concise walkthrough that incorporates a variety of Open Liberty respources in a straightforward manner. I'll open a PR to draft for some minor ID edits and send it for your review.

A few thoughts at a more conceptual level- bear with me, this post is my introduction to RealWorld :).

The intro to the post is really strong- it tells the reader why they should care and makes the task seem easy to try. I wonder though if you might be a bit more explicit in explaining the relationship between RealWorld, Conduit and Open Liberty, as I had to read a few times before I understood. 

If I'm understanding correctly:

- RealWorld provides a test app called Conduit, which you can use to audition different frontend and backend options, and see how different combinations work together.
- This blog configures an Open Liberty server, complete with auth & data source, that can serve as the backend server for a RealWorld instance of Conduit, which then you could presumably try out different frontend options for
- The JAX-RS app is just to give the OL server something to call to to verify Conduit startup- is that right? I'm not sure

One thing I noticed is that "Conduit" is only mentioned once in the intro. Since it's in the title as well, it seems like it is conspicuously missing from the rest of the post. Is it possible to tie the other parts of the post back to how they fit i n with the Conduit test app? Without further mention of conduit, it's also easier to confuse the JAX-RS app with the Conduit app provided by RealWorld.

You also might want to include a little more about the frontend- it's only really mentioned in the intro but its likely a reader who was going to try this out would have to make some decisions about it. Most of those decisions are outside of the scope of this post. However, including the frontend in your framework, at least conceptually, might help the reader to better map the task as a whole.

You do a really good job of setting the reader up in the intro, I think if you gave them a more explicit framework of the whole task (and not just the OL piece), it would help the reader build a mental map. 

I think you could adda short paragraph to the intro, 3-4 sentences, that walks through the concept as a whole- configuring a backend OL server and a JAX_RS app to test it, which you can then use as the backend for Conduit and try out different frontend options. You might even mention an example frontend option or options. Then tie it back in at the conclusion- the Try it Out section should tell the reader how they can use the server they configured w/ Conduit- eg choose a front end option. I feel like that gets lost a little bit. 

Does that make sense?

**Comment by dmuelle** [comment]
tentative publish date of 2/24

**Comment by gljrobinson** [comment]
Hi @dmuelle, I've moved this to Editing in Progress as I see you've already started editing and have sent some comments to the author. Thanks.
