### ISSUE TITLE
Blog about Long Running Actions (LRA) in Open Liberty beta

### ISSUE THREAD

**Issue by yongja79** [OpenLiberty/blogs#926]
Create a blog post about Microprofile Long Running Actions (LRA) that is now in the Open Liberty beta driver. Describe the basics on LRA and show an example of a coordinator and participant running on Open Liberty

**Comment by gljrobinson** [comment]
@Charlotte-Holt and @dmuelle ready for editing whenever you get the chance.

**Comment by dmuelle** [comment]
Starting on ID review for target publish date of 1/27

**Comment by dmuelle** [comment]
Hi @yongja79, I'm starting on the ID review and will open a PR to address any specific clarity/style/grammar concerns. From an overall content perspective, I'm wondering if it's possible to add an example scenario for LRA to the intro. Just a simple concrete application scenario so the user can get a sense of why they should care about LRA or in what circumstances they might need this information. 

I see the example at the end uses a travel/hotel booking service so that would be a great way to frame the application scenario. For a travel booking application- what problem might LRA solve?  I think you could change the title of the "What is a MicroProfile LRA?" section to "What are  long running actions?". Then add a paragraph that introduces a simple application scenario where LRA is useful, just a few sentences, no code. Then continue with the paragraph you already have about MPLRA. Giving the reader a concrete scenario before diving into the details of the spec will help orient them for the rest of the post. Let me know what you think

**Comment by yongja79** [comment]
@dmuelle , for the intro would something like:

"In the 20.0.0.12-beta release of Open Liberty a new capability was introduced to support loosely-coupled transaction semantics for Java microservice. This is an implementation of a new MicroProfile specification for Long Running Actions (MicroProfile LRA), which can be used to alleviate the challenges that traditional transaction models have in microservice architecture where you want to handle a distributed transaction across multiple services each of which has its own data."

As for the name of the section "What is a MicroProfile LRA?", the use of Microprofile was deliberate but we could change it to "What are Microprofile Long Running Actions?"

For the beginning of that section could be added:
"An example scenario where Microprofile LRA would be of use, would be a holiday booking system which has separate mircoservices to book a flight, book the hotel and book a taxi. To successfully book a holiday all three services must complete successfully and should any fail, all the completed steps must be rolled back. Thus you have a single transaction spanning multiple services and databases. "

Let me know what you think of those changes and whether I should add them.

**Comment by dmuelle** [comment]
@yongja79 - i think that sounds good. I would suggest adding the example scenario as the second paragraph in the "What is Microprofile LRA?" section. If you want to keep the section title as focused on the MP specification, probably better to introduce it, as you have it now, then add the example scenario.

After reading some of the spec, I agree that it makes sense to focus on MicroProfile LRA in the intro rather than LRA as a general concept. That said, I think "What is MicroProfile LRA?" is probably a better title than "What are MicroProfile Long Running Actions?" since the spec doesn't make clear between "action"/actions" and sometimes refers to "long running activities".

**Comment by gljrobinson** [comment]
@dmuelle can we close this now that it has been published?
